version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    environment:
      - DOCKER_HOST=tcp://docker:2375
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - docker
      - trivy

  docker:
    image: docker:dind
    container_name: docker-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    expose:
      - "2375"

  trivy:
    image: aquasec/trivy:latest
    container_name: trivy
    entrypoint: ["tail", "-f", "/dev/null"]  # Keeps Trivy container running
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Optional, for local image scanning

volumes:
  jenkins_home:
    external: true
    name: docker_jenkins_home  # Specify the external volume name correctly
